tarefa-1
flaviofmh/meucontrole pull request #1
Opened 2021-05-11 02:27 UTC by silva-wellington

Criado o projeto com a versão mais atualizado do Java (16) e do spring (2.4.5).
Adicionado as dependências:
- Web
- DevTools
- H2
- Lombok

2021-05-13 18:19 UTC, flaviofmh commented on src/test/java/com/gerenciador/meucontrole/MeucontroleApplicationTests.java
> +	void contextLoads() {
Teste vazio sem nada? Delete o teste que não esteja sendo usado

2021-05-13 18:21 UTC, flaviofmh requested changes
Fazer os devidos ajustes apontados no codigo

2021-05-13 18:21 UTC, flaviofmh commented on src/main/java/com/gerenciador/meucontrole/MeucontroleApplication.java
> +public class MeucontroleApplication {
MeuControleApplication, ficou errado o nome. Case sensitive.

2021-05-13 19:53 UTC, silva-wellington commented on src/test/java/com/gerenciador/meucontrole/MeucontroleApplicationTests.java
> +	void contextLoads() {
Verifica agora, fiz a exclusão.

2021-05-13 19:54 UTC, silva-wellington commented on src/main/java/com/gerenciador/meucontrole/MeucontroleApplication.java
> +public class MeucontroleApplication {
Renomeei a classe para o nome correto.

2021-05-13 19:55 UTC, silva-wellington commented
Feito as devidas correções.

2021-05-14 09:28 UTC, flaviofmh commented on .gitignore
> +.vscode/
https://github.com/spring-projects/spring-boot/blob/main/.gitignore usar o link para incluir igual no arquivo do gitignore

2021-05-14 11:03 UTC, flaviofmh approved these changes

2021-05-14 11:03 UTC, merged