Task-2 e Task-4
flaviofmh/meucontrole pull request #2
Opened 2021-05-24 02:56 UTC by silva-wellington

Adicionado os Resurcer POST e DELETE de Cliente.

2021-05-24 22:02 UTC, flaviofmh commented on src/main/java/com/gerenciador/meucontrole/controller/ClienteController.java
> +@RequestMapping("cliente")
Faltou a base de url de versionamento. Adicionar antes da url v1/ e deixar as urls organizadas em uma clss sendn atributos estáticos

2021-05-24 22:04 UTC, flaviofmh commented on src/main/java/com/gerenciador/meucontrole/controller/ClienteController.java
> +	@ResponseStatus(code = HttpStatus.OK)
Status response errado, deve ser o no content.

2021-05-24 22:05 UTC, flaviofmh commented on src/main/java/com/gerenciador/meucontrole/controller/ClienteController.java
> +		return ResponseEntity.ok().build();
Status response created. Retornar o objeto criado com o id.

2021-05-24 22:07 UTC, flaviofmh commented on src/main/java/com/gerenciador/meucontrole/controller/ClienteController.java
> +		return ResponseEntity.ok(clienteService.findAll());
O recurso deve retornar paginado. Usar o paginatin do spring.

2021-05-24 22:10 UTC, flaviofmh commented on src/main/java/com/gerenciador/meucontrole/model/ClienteContato.java
> +	public ClienteContato() {
Usar a anotação do lombok de contrutor com e sem argumentos.

2021-05-24 22:13 UTC, flaviofmh commented on src/main/java/com/gerenciador/meucontrole/repository/ClienteContatoRepository.java
> +public interface ClienteContatoRepository extends JpaRepository<ClienteContato, Long>  {
Usar o repository do cliente para fazer as operações de persistência de dados. Aplicar o principio de DDD

2021-05-24 22:16 UTC, flaviofmh requested changes
Fazer os ajustes apontados nos comentários. Qualquer dúvida de escopo técnico falar.

2021-05-25 01:35 UTC, silva-wellington commented on src/main/java/com/gerenciador/meucontrole/controller/ClienteController.java
> +@RequestMapping("cliente")
Havia colocado no application.properties na propriedade server.servlet.context-path=/v1.
Pode ser dessa forma?

2021-05-25 01:55 UTC, silva-wellington commented on src/main/java/com/gerenciador/meucontrole/controller/ClienteController.java
> +	@ResponseStatus(code = HttpStatus.OK)
Corrigido no commit 667b71e5b6bf0d1d9a4a71a6a5419c90feeb3c60

2021-05-25 02:04 UTC, silva-wellington commented on src/main/java/com/gerenciador/meucontrole/model/ClienteContato.java
> +	public ClienteContato() {
Corrigido no commit 0734045a0596f976e6ae5b41b84299637e619827

2021-05-25 02:22 UTC, silva-wellington commented on src/main/java/com/gerenciador/meucontrole/controller/ClienteController.java
> +		return ResponseEntity.ok().build();
Corrigido no commit 0a26c1a186af59bcd65b2432026345fcfea02493

2021-05-25 03:40 UTC, silva-wellington commented on src/main/java/com/gerenciador/meucontrole/controller/ClienteController.java
> +		return ResponseEntity.ok(clienteService.findAll());
Corrigido no commit eadd79c9c468fb2b74142bd449bf2c0f0121bea5

2021-05-25 22:37 UTC, silva-wellington commented on src/main/java/com/gerenciador/meucontrole/repository/ClienteContatoRepository.java
> +public interface ClienteContatoRepository extends JpaRepository<ClienteContato, Long>  {
Corrigido no commit 3be66e255960be62fa44269a78e97a1385a8db9b

2021-05-25 22:47 UTC, silva-wellington commented on src/main/java/com/gerenciador/meucontrole/controller/ClienteController.java
> +@RequestMapping("cliente")
Adicionado a classe no commit 3be66e255960be62fa44269a78e97a1385a8db9b

2021-05-26 19:52 UTC, flaviofmh approved these changes

2021-05-26 19:52 UTC, merged